filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true


setup.ilm.enabled: false

setup.template.name: "weflow-logs"
setup.template.pattern: "weflow-logs-*"
setup.template.enabled: true

output.elasticsearch:
  hosts: ["http://es:9200"]
  index: "weflow-logs-%{+yyyy.MM.dd}"

processors:
  - dissect:
      tokenizer: "API_CALL method=%{api_method} path=%{api_path} status=%{api_status} duration=%{duration_ms}ms"
      field: "message"
      target_prefix: ""
