package com.rdc.weflow_server.entity.notification;

public enum NotificationType {
    STEP_REQUEST,
    STEP_DECISION,
    NEW_POST,
    NEW_COMMENT,
    MENTION,
    SYSTEM_NOTICE,
    CHECKLIST_CREATED,
    CHECKLIST_SUBMITTED,
    PROJECT_CREATED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_COMPLETED,
    PROJECT_STATUS_CHANGED,
    PROJECT_INFO_UPDATED,
}
