package com.rdc.weflow_server.entity.notification;

public enum NotificationType {
    STEP_REQUEST,
    STEP_DECISION,
    NEW_POST,
    NEW_COMMENT,
    MENTION,
    SYSTEM_NOTICE,
    CHECKLIST_CREATED,
    CHECKLIST_SUBMITTED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_INFO_UPDATED,
    PROJECT_COMPLETED,
    PROJECT_STATUS_CHANGED,
    APPROVAL_REQUEST,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    TASK_ASSIGNED,
    TASK_COMPLETED
}
